### ISSUE TITLE
Fix Bugs left while changing CSS Files to CSS Module

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#369]
Deliverable:

- [ ] Fix `join us` button of home page
- [ ] Fix the width of the dash under the `HIT Tech Community` title of home page
- [ ] Fix `Subscribe to newsletter` section (the input box, it's alignment etc.)
- [ ] Fix the `All Broadcasts` button on Broadcasts page(It should appear in centre)

**Comment by LeeRenJie** [comment]
I would love to work on this! @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> I would love to work on this! @Kajol-Kumari

sure @LeeRenJie Please go ahead with this issue!
Happy Learning :)

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/107347270-9b068580-6b00-11eb-9ab0-4d37712811d0.png)
I realized that the button is not centered due to the "width 37%" from .main-button.main-button-2. I tried to change the width to 100% in the developer tools and it worked. But,
![image](https://user-images.githubusercontent.com/67599130/107347462-d012d800-6b00-11eb-8072-8800a03900e1.png)
Button 3 uses this style. I tried adding a className for this component but couldn't override the width to 100% but it could override. Any guidelines to solve this?

**Comment by Kajol-Kumari** [comment]
> ![image](https://user-images.githubusercontent.com/67599130/107347270-9b068580-6b00-11eb-9ab0-4d37712811d0.png)
> I realized that the button is not centered due to the "width 37%" from .main-button.main-button-2. I tried to change the width to 100% in the developer tools and it worked. But,
> ![image](https://user-images.githubusercontent.com/67599130/107347462-d012d800-6b00-11eb-8072-8800a03900e1.png)
> Button 3 uses this style. I tried adding a className for this component but couldn't override the width to 100% but it could override. Any guidelines to solve this?

Let me check it once on my end and get back to you :)

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/107357485-140bda00-6b0d-11eb-8779-ef221057810b.png)
If I changed the width from 37% to 100%, the buttons look good

Including this:
![image](https://user-images.githubusercontent.com/67599130/107357524-26861380-6b0d-11eb-854d-2250179388a5.png)

and this:
![image](https://user-images.githubusercontent.com/67599130/107357556-3140a880-6b0d-11eb-8260-efd440762b50.png)
