### ISSUE TITLE
[Document] Add bug and feature template for issues

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#42]
Deliverables:

- [ ] Template for bug report issue containing all the required the sections like {Current behaviour, expected behaviour, Related screenshot, Device used etc}

- [ ] Template for feature request issue containing all the required the sections like {Feature description, Related link.screenshot for referrence etc}

**Comment by SHITIZ-AGGARWAL** [comment]
I would like to work on this issue during SWOC

**Comment by Kajol-Kumari** [comment]
Sure @SHITIZ-AGGARWAL you can go ahead with this issue.

**Comment by jackfrost13** [comment]
@SHITIZ-AGGARWAL Please update your progress on this.

**Comment by SHITIZ-AGGARWAL** [comment]
I have started the work but I can commit after SWOC begins

**Comment by SHITIZ-AGGARWAL** [comment]
---
name: Bug report
about: Create a report to help us improve

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by jackfrost13** [comment]
@Kajol-Kumari Go through this once :+1:

**Comment by SHITIZ-AGGARWAL** [comment]
---
name: Feature request
about: Suggest an idea for this project

---

**Please describe about your feature request problem**
A clear and concise description of what the problem is

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context ,links or screenshots about the feature request here.

**Comment by Kajol-Kumari** [comment]
@SHITIZ-AGGARWAL Looks nice, will require few minor amendments, feel free to open up a PR as soon as SWOC commence

**Comment by SHITIZ-AGGARWAL** [comment]
@Kajol-Kumari sure
