### ISSUE TITLE
[Discussion] Implementation of Q&A Section in Website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#699]
### Feature Request -

- [ ] To have a Q&A section where our students can ask questions and relevant people can reply to that. 
- [ ] The question entered must be approved by admins in order to appear on the page
- [ ] The answers given must be approved by admins in order to appear on the page
- [ ] This section should be public on the website. 
- [ ] admins should only have the option to upvote and downvote answers. 
- [ ] Have tags in the question [ we can later-on use it for filtering purpose]
- [ ] Admins should have flexibility to improve the question&answers [Extension]

Need Ideas on-
1. Where we should keep this feature
2. How we should Implement it

### Flow:
Question asked => sent for approval[show proper message to user] => approved => comes on the Q&A page => Someone gives answer to it => sent for approval [show proper message to user]=> approved => comes under Q&A Page

Note - After we get a good enough proposal of it's implementation , the related issue will be assigned to the respective person for its implementation .

List of related issues-
#700 
[#728](https://github.com/HITK-TECH-Community/Community-Website/issues/728)
[#729](https://github.com/HITK-TECH-Community/Community-Website/issues/729)
[#730](https://github.com/HITK-TECH-Community/Community-Website/issues/730)

**Comment by sejalsingh417** [comment]
please assign this to me!

**Comment by Mobasherah12** [comment]
@Kajol-Kumari Shall we add a JWOC label as well?

**Comment by ikavyajain** [comment]
I think I can work on this issue. Can you assign it to me?
@Kajol-Kumari

**Comment by AnweshaRoses** [comment]
Hello If the issue is still not fixed I would love to work on it

**Comment by ikavyajain** [comment]
I’ll also like to work on it!

**Comment by himanshusanecha** [comment]
Some insights on how it can be implemented from the perspective of backend - 
Question model in mongoose - 
```
{
question: "some example question?",
answer: "initially empty",
status: 0, 1, 2 - 0 means question approval pending, 1 means question approved by admin.
tags: ['maths','computer science'] - array of tags,
owner: email of the user that posted this question
}
```
Answer model in mongoose - 
{
answer: "answer of the question",
questionID: id of the question to which we have answered,
upvotes: 10,
downvotes: 5,
status: 0 or 1 - 0 means answer approval pending, 1 means answer approved by admin.
}

With respect to the above schema various methods can be defined as mentioned below
1. Post question - so that user can post his/her question.
2. Get all questions asked by me - so that user can get a list of all the questions he/she has answered.
3. Approve question - so that admin can approve question. (after approval no edits can be made by the user on question)
4. answer question - so that any user can answer a particular question.
5. Approve answer - so that admin can approve answer.
6. upvote answer - so that user can upvote.
7. downvote answer - so that user can downvote answer

Reason behind not using parent or child referencing in answer and question because there can be multiple answers to a question and it can exceed the size of document in mongodb.

**Comment by sulogna2001** [comment]
Hello can you assign me this issue under GSSOC 22

**Comment by deepbeatz** [comment]
@himanshu1221  i want to work in this issue under JWOC

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by Kazasunitha** [comment]
I can work on this issue under GCCoS'24 .Hope you can label it with GCCoS'24 and assign it to me

**Comment by Kajol-Kumari** [comment]
> I can work on this issue under GCCoS'24 .Hope you can label it with GCCoS'24 and assign it to me

Hey @Kazasunitha  this issue was just for discussion, please check https://github.com/HITK-TECH-Community/Community-Website/issues/700 which is the only left out issue that came as output of this discussion
