### ISSUE TITLE
[Backend] Question tags are not getting saved correctly. 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#928]
**Describe the bug**
Write you fill the `Ask your Question` form, you select the tag, those tags aren't getting saved in backend.

**To Reproduce**
1. Go to `Q&A` section of the page - https://hitk-tech-community.netlify.app/q&a 
2. Click on `Ask your questino` and fill the form
3. Select the required tab. 
4. In db, the data is getting stored like below screenshot
<img width="911" alt="Screenshot 2024-05-18 at 10 38 25 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/f59daacf-1296-4700-bfda-c8241ebe1de1">

**Expected behaviour**
The correct tag should get saved in the db and should appear on the question card. currently just `#` appears. 
<img width="389" alt="Screenshot 2024-05-18 at 10 39 39 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/f982af3d-d048-4f21-8c15-7d8d185f1e56">

**Comment by dhyaneshsiddhartha15** [comment]
Hello @Kajol-Kumari , I've identified a bug in the Ask your Question form on the Q&A page. When selecting tags, they are not being saved to the backend, resulting in only '#' appearing on the question card. This is not the expected behavior. Could you please investigate and fix this issue? Assign me Under GSSOC'24 Label

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assign it to me ?
